global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8080']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8081']
  
  - job_name: 'profiles'
    static_configs:
      - targets: ['profiles:8080']

  - job_name: 'exercises'
    static_configs:
      - targets: ['exercises:8080']