server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Оставляем только контейнеры из нашего compose-проекта (чтобы не собирать все контейнеры на сервере)
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        regex: '.+'
        action: keep
      # Извлекаем имя контейнера
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      # Добавляем имя сервиса (из compose)
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      # Добавляем уровень логирования из JSON (если есть поле level)
      - source_labels: ['__json_level']
        target_label: level
      # Добавляем метод gRPC, если есть
      - source_labels: ['__json_method']
        target_label: method