syntax = "proto3";

package profiles;

option go_package = "internal/gen/api/profiles";

service ProfilesService {
  rpc GetMyProfile(GetMyProfileRequest) returns (UserProfile);
  rpc PatchMyProfile(PatchMyProfileRequest) returns (UserProfile);
  rpc DeleteMyProfile(DeleteMyProfileRequest) returns (DeleteMyProfileResponse);
  rpc GetProfile(GetProfileRequest) returns (UserProfile);
}

message GetMyProfileRequest {
    // пусто
}

message PatchMyProfileRequest {
  optional string sex        = 1;
  optional double weight_kg  = 2;
  optional string birth_date = 3;
  optional int32  height_cm  = 4;
}

message DeleteMyProfileRequest {
    // пусто
}

message GetProfileRequest {
  string user_id = 1;
}

message UserProfile {
  string user_id           = 1;
  string sex               = 2;
  double weight_kg         = 3;
  string birth_date        = 4;
  int32  height_cm         = 5;
  bool   profile_completed = 6;
}

message DeleteMyProfileResponse {
    // пусто
}